Krista Byers-Heinlein (Concordia University)1,
Angeline Sin Mei Tsui (Stanford University)2,
Christina Bergmann (Max Planck Institute for Psycholinguistics)3,
Alexis Black (University of British Columbia)4,
Anna Brown (University of Liverpool)5,
Maria Julia Carbajal (ENS, EHESS, CNRS, PSL University)6,
Samantha Durrant (University of Liverpool)5,
Christopher T. Fennell (University of Ottawa)7,
Anne-Caroline Fiévet (ENS, EHESS, CNRS, PSL University)6,
Michael C. Frank (Stanford University)2,
Anja Gampe (University of Zurich)8,
Judit Gervain (CNRS & Université Paris Descartes)9,
Nayeli Gonzalez-Gomez (Oxford Brookes University)10,
J. Kiley Hamlin (University of British Columbia)4,
Naomi Havron (ENS, EHESS, CNRS, PSL University)6,
Mikolaj Hernik (UiT The Arctic University of Norway)11,
Shila Kerr (McGill University)12,
Hilary Killam (Concordia University)1,
Kelsey Klassen (University of Manitoba)13,
Jessica Kosie (Princeton University)14,
Ágnes Melinda Kovács (Central European University)15,
Casey Lew-Williams (Princeton University)14,
Liquan Liu (Western Sydney University)16,
Caterina Marino (CNRS & Université Paris Descartes)9,
Meghan Mastroberardino (Concordia University)1,
Victoria Mateu (UCLA)17,
Clarie Noble (University of Liverpoo)5,
Adriel John Orena (McGill University)12,
Linda Polka (McGill University)12,
Christine E. Potter (Princeton University)14,
Leher Singh (National University of Singapore)18,
Melanie Soderstrom (University of Manitoba)13,
Megha Sundara (UCLA)17,
Connor Waddell (Western Sydney University)16,
Janet Werker (University of British Columbia)4,
Stephanie Wermelinger (University of Zurich)8.
